#!/opt/bin/bash
#
# Copyright (C) 2016 Tomato-shibby
# Copyright (C) 2016 Jian Chang <aa65535@live.com> && Jason Lin <wojiaolinmu008@gmail.com>
# Main author: Jian Chang && Jason Lin
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

#debug
#set -x

TAG="SS_SPEC"          # iptables tag
IPT="iptables -t nat"  # alias of iptables
IPSET="ss_spec"        # list of ipset

usage() {
	cat <<-EOF
		Usage: ss-rules [options]

		Valid options are:

		    -s <server_ip>          ip address of shadowsocks remote server
		    -l <local_port>         port number of shadowsocks local server
		    -i <ip_list_file>       a file content is bypassed ip list
		    -b <wan_ips>            wan ip of will be bypassed
		    -w <wan_ips>            wan ip of will be forwarded
		    -I <interface>          proxy only for the given interface
		    -d <target>             the default target of lan access control
		    -a <hosts_action>       lan ip of access control, need a prefix to
		                            define access control mode			
		    -e <extra_options>      extra options for iptables
		    -o                      apply the rules to the OUTPUT chain
		    -u                      enable udprelay mode, TPROXY is required
		    -G                      enable GFWLIST
		    -f                      flush the rules
		    -h                      show this help message and exit
EOF
	exit $1
}

loger() {
	# 1.alert 2.crit 3.err 4.warn 5.notice 6.info 7.debug
	logger -st ss-rules[$$] -p$1 $2
}

flush_r() {
	iptables-save -c | grep -v "$TAG" | \
	grep -v "gfw_black_list" | \
	iptables-restore -c 2>/dev/null
	ip rule del fwmark 0x01/0x01 table 100 2>/dev/null
	ip route del local 0.0.0.0/0 dev lo table 100 2>/dev/null
	for setname in $(ipset -n list | grep -i "$IPSET"); do
		ipset destroy $setname 2>/dev/null
	done
	ipset -X gfw_black_list 2>/dev/null
	return 0
}

gfw_r() {
	if [ "$GFWLIST" = 1 ]; then
		ipset -N gfw_black_list hash:ip hashsize 65536
		local JSON="/opt/etc/shadowsocks.json"
		local PORT=`sed -n 's/.*l_port": \(.*\)/\1/p' $JSON | sed 's/,//g'`
		$IPT -A PREROUTING -p tcp -m set --match-set gfw_black_list dst \
			-j REDIRECT --to-port $PORT
		$IPT -A OUTPUT -p tcp -m set --match-set gfw_black_list dst \
			-j REDIRECT --to-port $PORT
		touch a /var/log/gfwlist.lock
	fi
	return $?	
}
	
ipset_r() {
	ipset -! restore <<-EOF || return 1
		create ss_spec_lan_no hash:net hashsize 65536
		create ss_spec_lan_bp hash:net hashsize 65536
		create ss_spec_lan_fw hash:net hashsize 65536
		create ss_spec_wan_sp hash:net hashsize 65536
		create ss_spec_wan_bp hash:net hashsize 65536
		create ss_spec_wan_fw hash:net hashsize 65536
		$(gen_iplist | sed -e "s/^/add ss_spec_wan_sp /")
		$(sed -e "s/^/add ss_spec_wan_bp /" ${IGNORED:=/dev/null} 2>/dev/null)
		$(for ip in $WAN_BP_IP; do echo "add ss_spec_wan_bp $ip"; done)
		$(for ip in $WAN_FW_IP; do echo "add ss_spec_wan_fw $ip"; done)
EOF
	return 0
}

ac_rule() {
	for action in $LAN_HOSTS_ACTION; do
		case "${action:0:1}" in
			n|N)
				ipset add ss_spec_lan_no ${action:2}
				;;
			b|B)
				ipset add ss_spec_lan_bp ${action:2}
				;;
			g|G)
				ipset add ss_spec_lan_fw ${action:2}
				;;
		esac
	done
	include_ac_rules nat
	include_prerouting_rules nat
	$IPT -A SS_SPEC_WAN_FW -p tcp \
		-j REDIRECT --to-ports $local_port 2>/dev/null || {
		loger 3 "Can't redirect, please check the iptables."
		return 1
	}
	if [ "$OUTPUT" = 1 ]; then
		$IPT -I OUTPUT 1 -p tcp $EXT_ARGS -j SS_SPEC_WAN_AC
	fi
	return $?
}

tp_rule() {
	[ ! "`dmesg | grep TPROXY | wc -l`" -eq 2 ] && return 0
	[ -n "$TPROXY" ] || return 0
	ip rule add fwmark 0x01/0x01 table 100
	ip route add local 0.0.0.0/0 dev lo table 100
	local ipt="iptables -t mangle"
	include_ac_rules mangle
	include_prerouting_rules mangle
	$ipt -A SS_SPEC_WAN_FW -p udp -j TPROXY --on-port "$LOCAL_PORT" \
		--tproxy-mark 0x01/0x01
	return $?
}

include_ac_rules() {
	iptables-restore -n <<-EOF
	*$1
	:SS_SPEC_WAN_FW - [0:0]
	:SS_SPEC_WAN_AC - [0:0]
	:SS_SPEC_LAN_AC - [0:0]
	-A SS_SPEC_WAN_FW -m set --match-set ss_spec_wan_sp dst -j RETURN
	-A SS_SPEC_WAN_AC -m set --match-set ss_spec_wan_fw dst -j SS_SPEC_WAN_FW
	-A SS_SPEC_WAN_AC -m set --match-set ss_spec_wan_bp dst -j RETURN
	-A SS_SPEC_WAN_AC -j SS_SPEC_WAN_FW
	-A SS_SPEC_LAN_AC -m set --match-set ss_spec_lan_bp src -j RETURN
	-A SS_SPEC_LAN_AC -m set --match-set ss_spec_lan_fw src -j SS_SPEC_WAN_FW
	-A SS_SPEC_LAN_AC -m set --match-set ss_spec_lan_no src -j SS_SPEC_WAN_AC
	-A SS_SPEC_LAN_AC -j ${LAN_DEFAULT_TARGET:=SS_SPEC_WAN_AC}
	COMMIT
EOF
}

gen_prerouting_rules() {
	local protocol=$([ "$1" = "mangle" ] && echo udp || echo tcp)
	for ifname in $IFNAMES; do
		[ -z "$ifname" ] && continue
		local empty=no
		echo -I PREROUTING 1 -i $ifname -p $protocol $EXT_ARGS -j SS_SPEC_LAN_AC
	done
	if [ -z "$empty" ]; then
		echo -I PREROUTING 1 -p $protocol $EXT_ARGS -j SS_SPEC_LAN_AC
	fi
}

include_prerouting_rules() {
	iptables-restore -n <<-EOF
	*$1
	$(gen_prerouting_rules $1)
	COMMIT
EOF
}

gen_iplist() {
	cat <<-EOF | grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}"
		0.0.0.0/8
		10.0.0.0/8
		100.64.0.0/10
		127.0.0.0/8
		169.254.0.0/16
		172.16.0.0/12
		192.0.0.0/24
		192.0.2.0/24
		192.88.99.0/24
		192.168.0.0/16
		198.18.0.0/15
		198.51.100.0/24
		203.0.113.0/24
		224.0.0.0/4
		240.0.0.0/4
		255.255.255.255
		$server
EOF
}

while getopts ":s:l:i:b:w:I:d:a:e:ouGfh" arg; do
	case "$arg" in
		s)
			server=$OPTARG
			;;			
		l)
			local_port=$OPTARG
			;;
		i)
			IGNORED=$OPTARG
			;;
		b)
			WAN_BP_IP=$OPTARG
			;;
		w)
			WAN_FW_IP=$OPTARG
			;;
		I)
			IFNAMES=$OPTARG
			;;
		d)
			LAN_DEFAULT_TARGET=$OPTARG
			;;
		a)
			LAN_HOSTS_ACTION=$OPTARG
			;;
		e)
			EXT_ARGS=$OPTARG
			;;	
		o)
			OUTPUT=1
			;;
		u)
			TPROXY=1
			;;
		G)
			GFWLIST=1
			;;			
		f)
			flush_r
			exit 0
			;;
		h)
			usage 0
			;;
	esac
done

if [ "$GFWLIST" = 1 ]; then
	:	
else
	if [ -z "$server" -o -z "$local_port" ]; then
		usage 2
	fi
fi

if [ "$TPROXY" = 1 ]; then
	SERVER=$server
	LOCAL_PORT=$local_port
fi

if [ "$GFWLIST" = 1 ]; then
	flush_r && gfw_r
	RET=$?	
	[ "$?" = 0 ] && loger 6 "Load gfwlist successful" || loger 3 "Start failed!"
	touch /var/log/gfwlist.lock
	exit $RET
else
	flush_r && ipset_r && ac_rule && tp_rule
	RET=$?
	[ "$?" = 0 ] && loger 6 "Load chnroutes successful" || loger 3 "Start failed!"
	touch /var/log/chnroutes.lock
	exit $RET
fi