#!/bin/sh
#
# Copyright (C) 2016 Tomato-shibby
# Copyright (C) 2016 Jason Lin <wojiaolinmu008@gmail.com>
# Main author: Jason Lin && wojiaolinmu008
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

#set -x

if [ ! -d "/opt/etc/shadowsocks" ]; then
	mkdir -p /opt/etc/shadowsocks/WAN_AC_SP && \
	mkdir -p /opt/etc/shadowsocks/WAN_AC_FW && \
	mkdir -p /opt/etc/shadowsocks/WAN_AC_BP && \
	mkdir -p /opt/etc/shadowsocks/LAN_AC_NO && \	
	mkdir -p /opt/etc/shadowsocks/LAN_AC_FW && \
	mkdir -p /opt/etc/shadowsocks/LAN_AC_BP
fi

server_ip=`sed -n 's/.*ver": *"\(.*\)".*/\1/p' /opt/etc/shadowsocks.json`
local_port=`sed -n 's/.*l_port": *\(.*\)/\1/p' /opt/etc/shadowsocks.json | sed 's/,//g'`
ignore_list=/opt/etc/ignore.list
wan_ac_list_sp=/opt/etc/shadowsocks/WAN_AC_SP/wan_ac.list
wan_ac_list_fw=/opt/etc/shadowsocks/WAN_AC_FW/wan_ac.list
wan_ac_list_bp=/opt/etc/shadowsocks/WAN_AC_BP/wan_ac.list
lan_ac_list_no=/opt/etc/shadowsocks/LAN_AC_NO/lan_ac.list
lan_ac_list_fw=/opt/etc/shadowsocks/LAN_AC_FW/lan_ac.list
lan_ac_list_bp=/opt/etc/shadowsocks/LAN_AC_BP/lan_ac.list

[ ! -f "$wan_ac_list_fw" -o ! -f "$wan_ac_list_bp" ] && \
touch a $wan_ac_list_sp && \
touch a $wan_ac_list_fw && \
touch a $wan_ac_list_bp

[ ! -f "$lan_ac_list_in" -o ! -f "$lan_ac_list_out" ] && \
touch a $lan_ac_list_no && \
touch a $lan_ac_list_fw && \
touch a $lan_ac_list_bp

WAN_AC_NO=`sort -t'.' -nk1,1 -nk2,3 -nk3,3 -nk4,4 $wan_ac_list_sp | xargs`
WAN_AC_FW=`sort -t'.' -nk1,1 -nk2,3 -nk3,3 -nk4,4 $wan_ac_list_fw | xargs`
WAN_AC_BP=`sort -t'.' -nk1,1 -nk2,3 -nk3,3 -nk4,4 $wan_ac_list_bp | xargs`

LAN_AC_NO=`sort -t'.' -nk1,1 -nk2,3 -nk3,3 -nk4,4 $lan_ac_list_no | xargs`
LAN_AC_FW=`sort -t'.' -nk1,1 -nk2,3 -nk3,3 -nk4,4 $lan_ac_list_fw | xargs`
LAN_AC_BP=`sort -t'.' -nk1,1 -nk2,3 -nk3,3 -nk4,4 $lan_ac_list_bp | xargs`

PROCS=ss-nat
BIN=/opt/bin
START=$BIN/$PROCS
IFNAME=`nvram get lan_ifname`

$START -s $server_ip -l $local_port -i $ignore_list -o -e "-m multiport --dports 22,80,443" \
	-d SS_SPEC_WAN_AC \
	-I $IFNAME \
	-u
	